#!/usr/bin/env bash
# Your Bash script must accept 2 arguments:
# domain:
#	type: string
#	what: domain name to audit
#	mandatory: yes
# subdomain:
#	type: string
#	what: specific subdomain to audit
#	mandatory: no
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
# When only the parameter domain is provided, display information for its subdomains www, lb-01, web-01 and web-02 - in this specific order

display_info() {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        display_info "$1" "$subdomain"
    done
elif [ "$#" == 2 ]; then
    display_info "$1" "$2"
fi
