#!/usr/bin/env bash
# This debugging script ensures that Nginx must be running, and listening on port 80 of all the servers active IPv4 IPs

# remove default nginx file config
rm /etc/nginx/sites-enabled/default
# nginx config  to listen on port 80 for ll IPV4 Ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# nginx start
service nginx restart
