#!/usr/bin/env bash
# This script will display "To infinity and beyond" indefinitely"
# In between each iteration of the loop add "sleep 2"

while true
do
	echo "To infinity and beyond"
	sleep 2
done
