#!/usr/bin/env bash
# This script will display; "To infinity and beyond" indefinetly
# With a sleep 2 in between each iteration
# This will display "I am invincible!!!" when receiving a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I am invincible!!!"' SIGTERM
done
