#!/usr/bin/env bash
# This script will display numbers from 1 to 100
# Will display "FizzBuzz" when the number is a mutiple of 3 and 5
# Will display "Fizz" when number is a mutiple of 3
# Will display "Buzz" when the number is a mutiple of 5
# Otherwise, display the numbers and use a list format

for number in {1..100}
do
	if (( number % 3 == 0 && number % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( number % 3 == 0 ))
	then
		echo "Fizz"
	elif (( number % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$number"
	fi
done
