#!/usr/bin/env bash
# This script will display "Best School" 10 times using a while loop
# On the 9th iteration it displays "Hi"

k=0

while [ $k -lt 10 ]
do
	if [ $k -eq 9 ]
	then
		echo "Hi"
	fi

	echo "Best School"
	(( k++))
done
