#!/usr/bin/env bash
# This script loops from 1 t 10
# Will display "bad luck" for the 4th loop iteration
# Will display "good luck" for the 8th loop iteration
# Will display "Best School" for the other iterations
# Must use while loop, if, elif and else statements

k=0

while [ $k -lt 10 ]
do
	if [ $k -eq 3 ]
	then
		echo "bad luck"
	elif [ $k -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( k++ ))
done
