#!/usr/bin/env bash
# This script displays numbers 1 to 20
# Will display 4 and then "bad luck from China" for the 4th loop iteration
# Will display 9 and then "bad luck from Japan" for the 9th loop iteration
# Will display 17 and then "bad luck from Italy" for the 17th loop iteration
# Must use while loop and case statement

k=1

while [ $k -le 20 ]
do
	echo "$k"

	case $k in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac

	(( k++ ))

done
