#!/usr/bin/env bash
# This script will display the time for 12 hours and 59 minutes
# Will display hours from 0 to 12
# Will display minutes from 1 to 59
# Must use the while loop

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"

minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++))
done
