#!/usr/bin/env bash
# This script will display the content of the current directory
# In list format, without hidden files
# Must use for loop

list=$(ls)

for k in $list
do
	echo "$k" | cut -d '-' -f2
done
