#!/usr/bin/env bash
# Configure a ufw firewall to block all incoming trafic
# except for TCP ports 22, 80, and 443

sudo apt-get update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
sudo ufw status verbose
